name: Deploy

on:
  workflow_run:
    workflows: ['Docker']
    types: [completed]
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set Project Id
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Commit SHA as Tag
        id: set_sha
        run: echo "commit_sha=$(git rev-parse --short=7 ${{github.event.workflow_run.head_sha }})" >> $GITHUB_OUTPUT

      - name: Debug Tag
        run: |
          echo "Docker Image Tag: ${{ steps.set_sha.outputs.commit_sha }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.set_sha.outputs.commit_sha }} \
            --platform managed \
            --region ${{ secrets.CLOUD_RUN_REGION }} \
            --allow-unauthenticated \
            --set-env-vars PORT=3000,DB_USERNAME=${{ secrets.DB_USERNAME }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_NAME=${{ secrets.DB_NAME }},DB_HOST=${{ secrets.DB_HOST }},JWT_SECRET=${{ secrets.JWT_SECRET }}
