name: Docker

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: Build and push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Set Commit SHA as Tag
        id: set_sha
        run: echo "commit_sha=$(git rev-parse --short=7 ${{github.sha }})" >> $GITHUB_OUTPUT

      - name: Debug Tags
        run: |
          echo "Commit Tag: ${{ steps.set_sha.outputs.commit_sha }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.set_sha.outputs.commit_sha }} .
          echo "Build Docker Image with tag $tag"

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ steps.set_sha.outputs.commit_sha }}
          echo "Push Docker Image with tag $tag"
